### Exercici 1 

Crea un np.array d'una dimensió, que inclogui l'almenys 8 nombres sencers, data type int64. Mostra la dimensió i la forma de la matriu.

In [3]:
import numpy as np

myarray = np.array([4,5,8,7,6,9,1,2], dtype = np.int64)

print('Dimensions: ', myarray.ndim)
print('Forma: ', myarray.shape)

Dimensions:  1
Forma:  (8,)


### Exercici 2

De la matriu de l'exercici 1, calcula el valor mitjà dels valors introduïts
i resta la mitjana resultant de cada un dels valors de la matriu.

In [4]:
m = myarray.mean()
print('Original: ', myarray)
print('Valor mitja: ', m)
print('Resultat: ', np.subtract(myarray,m))


Original:  [4 5 8 7 6 9 1 2]
Valor mitja:  5.25
Resultat:  [-1.25 -0.25  2.75  1.75  0.75  3.75 -4.25 -3.25]


### Exercici 3

Crea una matriu bidimensional amb una forma de 5 x 5. Extreu el valor màxim de la matriu, i els valors màxims de cadascun dels seus eixos.

In [6]:
bidi = np.random.random((5,5))



print('Matriu original 5x5: \n', bidi)
print('\nValor maxim matriu: ', bidi.max())
print('Valors maxims eix 0 : ', bidi.max(axis=0))
print('Valors maxims eix 1 : ', bidi.max(axis=1))

Matriu original 5x5: 
 [[0.10899056 0.55171772 0.84349338 0.83867406 0.48027947]
 [0.81590769 0.87501964 0.70534967 0.835473   0.40656205]
 [0.27996338 0.04074565 0.14391467 0.40329962 0.59076435]
 [0.7399763  0.05161553 0.31404581 0.01510192 0.66672287]
 [0.79768748 0.52184295 0.75563963 0.35923093 0.42502305]]

Valor maxim matriu:  0.8750196413555081
Valors maxims eix 0 :  [0.81590769 0.87501964 0.84349338 0.83867406 0.66672287]
Valors maxims eix 1 :  [0.84349338 0.87501964 0.59076435 0.7399763  0.79768748]


### Exercici 4

Mostreu-me amb exemples de diferents matrius, la regla fonamental de Broadcasting que diu : "les matrius es poden transmetre / broadcast si les seves dimensions coincideixen o si una de les matrius té una mida d'1".

In [36]:
A = np.random.random((3))
B = np.random.random((3,3))
C = np.random.random((2,3))
D = np.random.random((2,4))
print('matriu A \n', A, '''A té una sola dimensió que es pot extendre al llarg de qualsevol matriu amb 
                                    una primera dimensió de longitud 3, per tant pot sumar-se tant a B i C
                                    pero no a D ja que tenen mesures diferents i no encaixen (al igual que
                                    B i C entre elles) \n''')
print('matriu B \n', B, '\n')
print('matriu C \n', C, '\n')
print('matriu D \n', D, '\n')
print('A+B \n', A+B, '\n')
print('A+C \n', A+C, '\n')
print('B+B \n', B+B, 'B sumada a ella mateixa es un exemple de coincidencia de dimensions \n')
print('A+D en canvi ens donara error perque els tamanys no coincideixen')
print('A+D \n', A+D, '\n')


matriu A 
 [0.75954308 0.92419141 0.82852198] A té una sola dimensió que es pot extendre al llarg de qualsevol matriu amb 
                                    una primera dimensió de longitud 3, per tant pot sumar-se tant a B i C
                                    pero no a D ja que tenen mesures diferents i no encaixen (al igual que
                                    B i C entre elles) 

matriu B 
 [[0.69546795 0.42224877 0.37888741]
 [0.46257643 0.65527899 0.87381112]
 [0.85573793 0.25540876 0.71475714]] 

matriu C 
 [[0.56720484 0.56021604 0.1168509 ]
 [0.14519159 0.68237794 0.22267299]] 

matriu D 
 [[0.75190344 0.31691496 0.49911381 0.86877052]
 [0.58870338 0.72334782 0.6089209  0.37614631]] 

A+B 
 [[1.45501103 1.34644018 1.20740939]
 [1.22211951 1.5794704  1.70233311]
 [1.61528101 1.17960018 1.54327913]] 

A+C 
 [[1.32674792 1.48440745 0.94537288]
 [0.90473467 1.60656935 1.05119497]] 

B+B 
 [[1.39093591 0.84449754 0.75777482]
 [0.92515285 1.31055798 1.74762225]
 [1.71147586 0

ValueError: operands could not be broadcast together with shapes (3,) (2,4) 

### Exercici 5

Utilitza la Indexació per extreure els valors d'una columna i una fila de la matriu. I suma els seus valors.

In [32]:
row1 = bidi[0]
print('Primera fila \n',row1)

col2 = bidi[:,1]
print('\nSegona columna \n', col2)

print('\nSuma :', row1 + col2)

Primera fila 
 [0.10899056 0.55171772 0.84349338 0.83867406 0.48027947]

Segona columna 
 [0.55171772 0.87501964 0.04074565 0.05161553 0.52184295]

Suma : [0.66070828 1.42673736 0.88423903 0.89028959 1.00212242]


### Exercici 6

Mask la matriu anterior, realitzeu un càlcul booleà vectoritzat, agafant cada element i comprovant si es divideix uniformement per quatre.

Això retorna una matriu de mask de la mateixa forma amb els resultats elementals del càlcul.